# swagger.yml

openapi: 3.0.0
info:
  title: "RP Flask REST API"
  description: "An API about people and notes"
  version: "1.0.0"

servers:
  - url: "/api"

components:
  schemas:
    Person:
      type: "object"
      required:
        - lname
      properties:
        fname:
          type: "string"
        lname:
          type: "string"
  parameters:
    lname:
      name: "lname"
      description: "last name of the person parameter"
      in: path
      required: True
      schema:
        type: "string"

paths:
  /people:
    get:
      operationId: "people.read_all"
      tags:
        - "People"
      summary: "Read the list of people"
      responses:
        "200":
          description: "Successfully read people list"
    post:
      operationId: "people.add_person"
      tags:
        - "Add person"
        - "Peoples"
        - "More Peoples"
      summary: "Adding peoples to in-memory database"
      responses:
        "201":
          description: "Added the person!"
      requestBody:
        description: "Person to create"
        required: True
        content:
          application/json:
            schema:
              x-body-name: "person"
              $ref: "#/components/schemas/Person"
  /people/{lname}:
    get:
      operationId: "people.get_a_person"
      tags:
        - "Get person by last name"
      summary: "Getting a single person"
      parameters:
        - $ref: "#/components/parameters/lname"
      responses:
        "200":
          description: "Found and sent!"
    put:
      operationId: "people.update_a_person"
      tags:
        - "Update names of a person"
      summary: "Updating the name of the person by searching last name"
      parameters:
        - $ref: "#/components/parameters/lname"
      responses:
        "200":
          description: "Values updated"
      requestBody:
        content:
          application/json:
            schema:
              x-body-name: "person"
              $ref: "#/components/schemas/Person"
    delete:
      operationId: "people.delete"
      tags:
        - "Delete a person from the dataset"
      summary: "Deleting a person from the dataset"
      parameters:
        - $ref: "#/components/parameters/lname"
      responses:
        "204":
          description: "Deleted the person"